CREATE TABLE IF NOT EXISTS schedules(
    game_id text PRIMARY KEY,
    season int,
    week int,
    gameday text,
    weekday text,
    away_team text,
    home_team text,
    home_score int,
    away_score int,
    result int,
    away_rest int,
    home_rest int,
    away_moneyline int,
    home_moneyline int,
    spread_line real,
    total_line real,
    under_odds int,
    over_odds int
);
CREATE TABLE IF NOT EXISTS team_stats(
    season int,
    team text,
    week int,
    game_id text,
    opponent_team text,
    passing_yards int,
    passing_tds int,
    passing_interceptions int,
    passing_epa real,
    passing_cpoe real,
    passing_40 int,
    rushing_yards int,
    rushing_tds int,
    rushing_epa real,
    rushing_40 int,
    receiving_yards int,
    receiving_tds int,
    receiving_epa real,
    receiving_40 int,
    receiving_yards_after_catch int,
    sack_fumbles_lost int,
    rushing_fumbles_lost int,
    receiving_fumbles_lost int,
    def_sacks real,
    def_interceptions int,
    def_tds int,
    def_tackles_for_loss int,
    fg_made int,
    fg_att int,
    pat_pct real,

    PRIMARY KEY (season,team,week)
);